[package]
name = "bagel_render-3d"
version = "0.1.0"
authors = ["Viktor Doroshenko <reg.doroshenko@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
